// Auto-generated by generate-search-data.js. Do not edit by hand.
// Run: node generate-search-data.js
window.LEADSPITCH_SEARCH_DATA = {
  "niches": [
    {
      "name": "Accounting & Finance",
      "slug": "accounting-finance",
      "url": "industries/accounting-finance.html",
      "desc": "CPAs, bookkeepers, financial advisors, and accounting firms. Verified contacts for B2B outreach.",
      "keywords": [
        "cpa",
        "bookkeeper",
        "accounting",
        "finance",
        "tax",
        "financial advisor",
        "audit"
      ],
      "plans": [
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Starter",
          "emails": "5K",
          "leads": "23K",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/starter-accounting-finance"
        },
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Growth",
          "emails": "25K",
          "leads": "82K",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/growth-accounting-finance"
        },
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Professional",
          "emails": "50K",
          "leads": "135K",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/professional-accounting-finance"
        },
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Business",
          "emails": "65K",
          "leads": "185K",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/business-accounting-finance"
        },
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Starter",
          "emails": "5K",
          "leads": "16K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/starter-accounting-finance-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Growth",
          "emails": "10.5K",
          "leads": "33K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/growth-accounting-finance-monthly-data-plan-for-6-months"
        },
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Professional",
          "emails": "16K",
          "leads": "48K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/professional-accounting-finance-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Accounting & Finance",
          "slug": "accounting-finance",
          "plan": "Business",
          "emails": "21K",
          "leads": "66K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/accounting-finance-leadspitch/business-accounting-finance-monthly-data-plan-for-12-months"
        }
      ]
    },
    {
      "name": "Agencies & Business",
      "slug": "agencies-business",
      "url": "industries/agencies-business.html",
      "desc": "Businesses that sell to other businesses. SaaS, agencies, consultants, and vendors.",
      "keywords": [
        "agency",
        "marketing",
        "saas",
        "consultant",
        "b2b",
        "vendor",
        "business services"
      ],
      "plans": [
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Starter",
          "emails": "5K",
          "leads": "26K",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/starter-agencies-business-services/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Growth",
          "emails": "25K",
          "leads": "100K",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/growth-agencies-business-services/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Professional",
          "emails": "50K",
          "leads": "170K",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/professional-agencies-business-services/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Business",
          "emails": "100K",
          "leads": "350K",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/business-agencies-business-services/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Enterprise",
          "emails": "300K",
          "leads": "1.05M+",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/enterprise-agencies-business-services/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Starter - Agencies & Business Services Monthly Data Plan for 12 Months",
          "emails": "25K",
          "leads": "88K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/starter-agencies-business-services-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Growth - Agencies & Business Services Monthly Data Plan for 6 Months",
          "emails": "50K",
          "leads": "176K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/growth-agencies-business-services-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Professional - Agencies & Business Services Monthly Data Plan for 4 Months",
          "emails": "75K",
          "leads": "264K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/professional-agencies-business-services-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Agencies & Business",
          "slug": "agencies-business",
          "plan": "Business",
          "emails": "100K",
          "leads": "352K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/agencies-business-services/business-agencies-business-services-monthly-data-plan-for-3-months/"
        }
      ]
    },
    {
      "name": "Automotive",
      "slug": "automotive",
      "url": "industries/automotive.html",
      "desc": "Dealerships, repair shops, auto parts stores, and car washes. Ready for partnership outreach.",
      "keywords": [
        "dealership",
        "car",
        "repair",
        "auto parts",
        "mechanic",
        "vehicle",
        "truck"
      ],
      "plans": [
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Starter",
          "emails": "5K",
          "leads": "27K",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/starter-automotive"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Growth",
          "emails": "25K",
          "leads": "105K",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/growth-automotive"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Professional",
          "emails": "50K",
          "leads": "180K",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/professional-automotive"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Business",
          "emails": "100K",
          "leads": "375K",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/business-automotive"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Scale",
          "emails": "200k",
          "leads": "650k",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/scale-automotive"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Enterprise",
          "emails": "300K",
          "leads": "1.15M+",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/enterprise-automotive"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Starter",
          "emails": "25K",
          "leads": "95K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/starter-automotive-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Growth",
          "emails": "50K",
          "leads": "190K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/growth-automotive-monthly-data-plan-for-6-months"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Professional",
          "emails": "75K",
          "leads": "285K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/professional-automotive-monthly-data-plan-for-4-months"
        },
        {
          "niche": "Automotive",
          "slug": "automotive",
          "plan": "Business",
          "emails": "100K",
          "leads": "380K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/automotive-leadspitch/business-automotive-monthly-data-plan-for-3-months"
        }
      ]
    },
    {
      "name": "Beauty & Wellness",
      "slug": "beauty-wellness",
      "url": "industries/beauty-wellness.html",
      "desc": "Salons, spas, wellness centers, and beauty businesses. Verified contacts for B2B outreach.",
      "keywords": [
        "salon",
        "spa",
        "beauty",
        "wellness",
        "massage",
        "fitness",
        "nails",
        "hair"
      ],
      "plans": [
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Starter",
          "emails": "5K",
          "leads": "28K",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/starter-beauty-and-wellness/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Growth",
          "emails": "25K",
          "leads": "100K",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/growth-beauty-and-wellness/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Professional",
          "emails": "50K",
          "leads": "165K",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/professional-beauty-and-wellness/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Business",
          "emails": "100K",
          "leads": "340K",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/business-beauty-and-wellness/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Enterprise",
          "emails": "160K",
          "leads": "560K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/enterprise-beauty-and-wellness/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Starter",
          "emails": "13K",
          "leads": "45K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/beauty-and-wellness-starter-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Growth",
          "emails": "27K",
          "leads": "95K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/beauty-and-wellness-growth-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Professional",
          "emails": "40K",
          "leads": "145K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/beauty-and-wellness-professional-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Beauty & Wellness",
          "slug": "beauty-wellness",
          "plan": "Business",
          "emails": "54K",
          "leads": "195K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/beauty-and-welness-leadspitch/beauty-and-wellness-business-monthly-data-plan-for-3-months/"
        }
      ]
    },
    {
      "name": "Clinics & Healthcare",
      "slug": "clinics",
      "url": "industries/clinics.html",
      "desc": "Practices, clinics, hospitals, and healthcare providers. Industry-specific contact data.",
      "keywords": [
        "clinic",
        "healthcare",
        "hospital",
        "doctor",
        "medical",
        "practice",
        "physician"
      ],
      "plans": [
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Starter",
          "emails": "5",
          "leads": "000",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/starter-clinics-leads"
        },
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Growth ⭐",
          "emails": "25",
          "leads": "000",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/growth-clinics-leads"
        },
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Professional",
          "emails": "50",
          "leads": "000",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/professional-clinics-leads"
        },
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Business",
          "emails": "100",
          "leads": "000",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/business-clinics-leads"
        },
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Starter",
          "emails": "8K",
          "leads": "42K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/clinics-starter-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Growth ⭐",
          "emails": "17K",
          "leads": "89K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/clinics-growth-monthly-data-plan-for-6-months"
        },
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Professional",
          "emails": "25K",
          "leads": "132K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/clinics-professional-monthly-data-plan-for-4-months"
        },
        {
          "niche": "Clinics & Healthcare",
          "slug": "clinics",
          "plan": "Business",
          "emails": "34K",
          "leads": "180K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/health-care-leads/clinics-business-monthly-data-plan-for-3-months"
        }
      ]
    },
    {
      "name": "Construction",
      "slug": "construction",
      "url": "industries/construction.html",
      "desc": "Contractors, builders, suppliers, and trade professionals. Verified data for B2B outreach.",
      "keywords": [
        "contractor",
        "builder",
        "construction",
        "subcontractor",
        "electrical",
        "plumbing",
        "hvac"
      ],
      "plans": [
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Starter",
          "emails": "5K",
          "leads": "26K",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/starter-construction-contractors"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Growth",
          "emails": "25K",
          "leads": "105K",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/growth-construction-contractors"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Professional",
          "emails": "50K",
          "leads": "175K",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/professional-construction-contractors"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Business",
          "emails": "100K",
          "leads": "360K",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/business-construction-contractors"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Scale",
          "emails": "200K",
          "leads": "760K",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/scale-construction-contractors"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Enterprise",
          "emails": "350K",
          "leads": "1.3M+",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/enterprise-construction-contractors"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Starter",
          "emails": "30K",
          "leads": "110K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/starter-construction-contractors-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Growth",
          "emails": "60K",
          "leads": "220K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/growth-construction-contractors-monthly-data-plan-for-6-months"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Professional",
          "emails": "90K",
          "leads": "320K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/professional-construction-contractors-monthly-data-plan-for-3-months"
        },
        {
          "niche": "Construction",
          "slug": "construction",
          "plan": "Business",
          "emails": "120K",
          "leads": "430K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/construction-contractors-leadspitch/business-construction-contractors-monthly-data-plan-for-3-months"
        }
      ]
    },
    {
      "name": "Dentists",
      "slug": "dentists",
      "url": "industries/dentists.html",
      "desc": "Dental practices, orthodontists, oral surgeons, and dental labs. Verified contacts for outreach.",
      "keywords": [
        "dentist",
        "dental",
        "orthodontist",
        "oral surgeon",
        "dental lab",
        "teeth"
      ],
      "plans": [
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Starter",
          "emails": "5K",
          "leads": "28K",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/starter-dentist-leads"
        },
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Growth ⭐",
          "emails": "25K",
          "leads": "95K",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/growth-dentist-leads"
        },
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Professional",
          "emails": "50K",
          "leads": "145K",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/professional-dentist-leads"
        },
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Business",
          "emails": "100K",
          "leads": "330K",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/business-dentist-leads"
        },
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Starter",
          "emails": "9K",
          "leads": "50K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/dentists-starter-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Growth ⭐",
          "emails": "19K",
          "leads": "105K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/dentists-growth-monthly-data-plan-for-6-months"
        },
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Professional",
          "emails": "28K",
          "leads": "155K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/dentists-professional-monthly-data-plan-for-4-months"
        },
        {
          "niche": "Dentists",
          "slug": "dentists",
          "plan": "Business",
          "emails": "38K",
          "leads": "210K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/destists-leads/dentists-business-monthly-data-plan-for-3-months"
        }
      ]
    },
    {
      "name": "Education & Training",
      "slug": "education",
      "url": "industries/education.html",
      "desc": "Schools, universities, training centers, and education providers. Industry-specific contact data.",
      "keywords": [
        "school",
        "university",
        "college",
        "education",
        "training",
        "academy",
        "learning"
      ],
      "plans": [
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Starter",
          "emails": "5K",
          "leads": "25K",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/starter-education-training"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Growth",
          "emails": "25K",
          "leads": "95K",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/growth-education-training"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Professional",
          "emails": "50K",
          "leads": "155K",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/professional-education-training"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Business",
          "emails": "100K",
          "leads": "330K",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/business-education-training"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Enterprise",
          "emails": "175K",
          "leads": "590K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/enterprise-education-training"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Starter",
          "emails": "14.5K",
          "leads": "50K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/starter-education-training-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Growth",
          "emails": "29.5K",
          "leads": "100K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/growth-education-training-monthly-data-plan-for-6-months"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Professional",
          "emails": "44K",
          "leads": "150K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/professional-education-training-monthly-data-plan-for-4-months"
        },
        {
          "niche": "Education & Training",
          "slug": "education",
          "plan": "Business",
          "emails": "69K",
          "leads": "200K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/education-training-c476/business-education-training-monthly-data-plan-for-12-months/"
        }
      ]
    },
    {
      "name": "Events & Leisure",
      "slug": "events-leisure",
      "url": "industries/events-leisure.html",
      "desc": "Venues, event planners, entertainment companies, and leisure businesses. Ready for outreach.",
      "keywords": [
        "event",
        "venue",
        "entertainment",
        "leisure",
        "planner",
        "recreation",
        "concert"
      ],
      "plans": [
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Starter",
          "emails": "5K",
          "leads": "26K",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/starter-events-leisure/"
        },
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Growth",
          "emails": "25K",
          "leads": "95K",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/growth-events-leisure/"
        },
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Professional",
          "emails": "50K",
          "leads": "155K",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/professional-events-leisure/"
        },
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Business",
          "emails": "110K",
          "leads": "330K",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/business-events-leisure/"
        },
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Starter",
          "emails": "9K",
          "leads": "30K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/starter-events-leisure-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Growth",
          "emails": "18K",
          "leads": "60K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/growth-events-leisure-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Professional",
          "emails": "27K",
          "leads": "90K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/professional-events-leisure-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Events & Leisure",
          "slug": "events-leisure",
          "plan": "Business",
          "emails": "37K",
          "leads": "125K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/events-leisure-leadspitch/business-events-leisure-monthly-data-plan-for-3-months/"
        }
      ]
    },
    {
      "name": "Food & Beverage",
      "slug": "food-beverage",
      "url": "industries/food-beverage.html",
      "desc": "Restaurants, cafes, food trucks, and catering businesses. Verified data for targeted campaigns.",
      "keywords": [
        "food",
        "beverage",
        "restaurant",
        "supplier",
        "catering",
        "distributor",
        "manufacturer"
      ],
      "plans": [
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Starter",
          "emails": "5K",
          "leads": "26K",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/starter-food-beverage-suppliers/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Growth",
          "emails": "25K",
          "leads": "95K",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/growth-food-beverage-suppliers/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Professional",
          "emails": "50K",
          "leads": "165K",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/professional-food-beverage-suppliers/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Business",
          "emails": "100K",
          "leads": "340K",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/business-food-beverage-suppliers/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Enterprise",
          "emails": "170K",
          "leads": "620K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/enterprise-food-beverage-suppliers/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Starter",
          "emails": "14K",
          "leads": "50K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/starter-food-beverage-suppliers-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Growth",
          "emails": "28K",
          "leads": "100K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/growth-food-beverage-suppliers-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Professional",
          "emails": "42K",
          "leads": "150K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/professional-food-beverage-suppliers-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Food & Beverage",
          "slug": "food-beverage",
          "plan": "Business",
          "emails": "56K",
          "leads": "200K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/food-beverage-suppliers/business-food-beverage-suppliers-monthly-data-plan-for-3-months/"
        }
      ]
    },
    {
      "name": "Home Services",
      "slug": "home-services",
      "url": "industries/home-services.html",
      "desc": "Plumbers, electricians, HVAC, landscapers, and home improvement pros. Verified contacts.",
      "keywords": [
        "plumber",
        "electrician",
        "hvac",
        "landscaper",
        "home",
        "handyman",
        "cleaning",
        "pest"
      ],
      "plans": [
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Starter",
          "emails": "5K",
          "leads": "26K",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/starter-home-services/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Growth",
          "emails": "25K",
          "leads": "100K",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/growth-home-services/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Professional",
          "emails": "50K",
          "leads": "170K",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/professional-home-services/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Business",
          "emails": "100K",
          "leads": "350K",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/business-home-services/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Scale",
          "emails": "200K",
          "leads": "700K",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/scale-home-services/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Enterprise",
          "emails": "300K",
          "leads": "1.05M",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/enterprise-home-services/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Complete Database",
          "emails": "430K+",
          "leads": "1.5M+",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/complete-database-home-services/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Starter",
          "emails": "36K",
          "leads": "125K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/starter-home-services-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Growth",
          "emails": "72K",
          "leads": "250K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/growth-home-services-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Professional",
          "emails": "108K",
          "leads": "375K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/professional-home-services-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Home Services",
          "slug": "home-services",
          "plan": "Business",
          "emails": "144K",
          "leads": "500K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/home-services-leadspitch/business-home-services-monthly-data-plan-for-3-months/"
        }
      ]
    },
    {
      "name": "Hotels & Hospitality",
      "slug": "hotels-hospitality",
      "url": "industries/hotels-hospitality.html",
      "desc": "Hotels, travel agencies, tour operators, and hospitality businesses. Verified contacts.",
      "keywords": [
        "hotel",
        "hospitality",
        "travel",
        "resort",
        "bnb",
        "tourism",
        "lodging"
      ],
      "plans": [
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Starter",
          "emails": "5K",
          "leads": "25K",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/starter-hotels-hospitality"
        },
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Growth",
          "emails": "25K",
          "leads": "90K",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/growth-hotels-hospitality"
        },
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Professional",
          "emails": "50K",
          "leads": "155K",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/professional-hotels-hospitality"
        },
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Business",
          "emails": "75K",
          "leads": "250K",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/business-hotels-hospitality"
        },
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Starter",
          "emails": "6.5K",
          "leads": "22K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/starter-hotels-hospitality-monthly-data-plan-for-12-months"
        },
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Growth",
          "emails": "13K",
          "leads": "44K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/growth-hotels-hospitality-monthly-data-plan-for-6-months"
        },
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Professional",
          "emails": "19K",
          "leads": "66K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/professional-hotels-hospitality-monthly-data-plan-for-4-months"
        },
        {
          "niche": "Hotels & Hospitality",
          "slug": "hotels-hospitality",
          "plan": "Business",
          "emails": "26K",
          "leads": "88K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/hotels-hospitality/business-hotels-hospitality-monthly-data-plan-for-12-months"
        }
      ]
    },
    {
      "name": "Legal",
      "slug": "legal",
      "url": "industries/legal.html",
      "desc": "Law firms, attorneys, paralegals, and legal service providers. Verified data for B2B outreach.",
      "keywords": [
        "lawyer",
        "attorney",
        "law firm",
        "legal",
        "paralegal",
        "solicitor"
      ],
      "plans": [
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Starter",
          "emails": "5K",
          "leads": "24K",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/starter-lawyer-leads/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Growth",
          "emails": "25K",
          "leads": "90K",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/growth-lawyer-leads/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Professional",
          "emails": "50K",
          "leads": "145K",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/professional-lawyer-leads/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Business",
          "emails": "100K",
          "leads": "300K",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/business-lawyer-leads/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Enterprise",
          "emails": "300K",
          "leads": "900K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/enterprise-lawyer-leads/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Starter",
          "emails": "25K",
          "leads": "75K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/lawyers-starter-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Growth",
          "emails": "50K",
          "leads": "150K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/lawyers-growth-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Professional",
          "emails": "75K",
          "leads": "225K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/lawyers-professional-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Legal",
          "slug": "legal",
          "plan": "Business",
          "emails": "100K",
          "leads": "300K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/legal-leadspitch/lawyers-enterprise-monthly-data-plan-for-3-months/"
        }
      ]
    },
    {
      "name": "Logistics",
      "slug": "logistics",
      "url": "industries/logistics.html",
      "desc": "Freight, warehousing, shipping, and transportation companies. Verified contacts for partnerships.",
      "keywords": [
        "logistics",
        "freight",
        "warehouse",
        "shipping",
        "trucking",
        "transportation",
        "supply chain"
      ],
      "plans": [
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Starter",
          "emails": "5K",
          "leads": "24K",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/starter-logistics-and-others/"
        },
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Growth",
          "emails": "25K",
          "leads": "85K",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/growth-logistics-and-others/"
        },
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Professional",
          "emails": "50K",
          "leads": "140K",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/professional-logistics-and-others/"
        },
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Business",
          "emails": "85K",
          "leads": "255K",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/business-logistics-and-others/"
        },
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Starter",
          "emails": "7K",
          "leads": "21K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/starter-logistics-and-others-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Growth",
          "emails": "14K",
          "leads": "42K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/growth-logistics-and-others-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Professional",
          "emails": "21K",
          "leads": "63K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/professional-logistics-and-others-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Logistics",
          "slug": "logistics",
          "plan": "Business",
          "emails": "28K",
          "leads": "84K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/logistics-and-others/business-logistics-and-others-monthly-data-plan-for-3-months/"
        }
      ]
    },
    {
      "name": "Real Estate",
      "slug": "real-estate",
      "url": "industries/real-estate.html",
      "desc": "Brokerages, agents, property managers, and real estate developers. Verified contacts for partnerships.",
      "keywords": [
        "real estate",
        "realtor",
        "broker",
        "property",
        "agent",
        "landlord",
        "developer"
      ],
      "plans": [
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Starter",
          "emails": "000",
          "leads": "3",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/real-estate-leades-1k/"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Growth",
          "emails": "000",
          "leads": "8",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/growth-real-estate-leads"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Professional ⭐",
          "emails": "000",
          "leads": "16",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/professional-real-estate-leads"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Business",
          "emails": "000",
          "leads": "32",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/business-real-estate-leads-83/"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Scale",
          "emails": "000",
          "leads": "80",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/scale-real-estate-leads"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Enterprise",
          "emails": "000",
          "leads": "160",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/enterprise-real-estate-leads"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Starter",
          "emails": "5k",
          "leads": "~15",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/real-estate-starter-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Growth",
          "emails": "10",
          "leads": "000",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/real-estate-growth-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Professional",
          "emails": "15",
          "leads": "000",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/real-estate-professional-monthly-data-plan-for-4-months"
        },
        {
          "niche": "Real Estate",
          "slug": "real-estate",
          "plan": "Business",
          "emails": "20",
          "leads": "000",
          "price": null,
          "member": null,
          "link": "https://whop.com/real-estate-leads-d0ea/real-estate-business-monthly-data-plan-for-3-months"
        }
      ]
    },
    {
      "name": "Restaurants & Cafes",
      "slug": "restaurants-cafes",
      "url": "industries/restaurants-cafes.html",
      "desc": "Restaurants, cafes, coffee shops, bakeries, and food businesses. Verified data for targeted campaigns.",
      "keywords": [
        "restaurant",
        "cafe",
        "coffee",
        "bakery",
        "dining",
        "bar",
        "catering"
      ],
      "plans": [
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Starter",
          "emails": "5K",
          "leads": "28K",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/starter-restaurants-cafes/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Growth",
          "emails": "25K",
          "leads": "100K",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/growth-restaurants-cafes/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Professional",
          "emails": "50K",
          "leads": "170K",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/professional-restaurants-cafes/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Business",
          "emails": "100K",
          "leads": "360K",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/business-restaurants-cafes/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Enterprise",
          "emails": "200K",
          "leads": "760K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/enterprise-restaurants-cafes/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Starter",
          "emails": "17K",
          "leads": "60K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/starter-restaurants-cafes-monthly-data-plan-for-12-months/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Growth",
          "emails": "34K",
          "leads": "120K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/growth-restaurants-cafes-monthly-data-plan-for-6-months/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Professional",
          "emails": "50K",
          "leads": "180K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/professional-restaurants-cafes-monthly-data-plan-for-4-months/"
        },
        {
          "niche": "Restaurants & Cafes",
          "slug": "restaurants-cafes",
          "plan": "Business",
          "emails": "67K",
          "leads": "240K+",
          "price": null,
          "member": null,
          "link": "https://whop.com/restaurants-cafes/business-restaurants-cafes-monthly-data-plan-for-3-months/"
        }
      ]
    }
  ],
  "bundles": [
    {
      "name": "Restaurants, Hotels & Construction",
      "desc": "Bundle of Restaurants & Cafes + Hotels & Hospitality + Construction datasets. Save up to $46.",
      "includes": [
        "Restaurants & Cafes",
        "Hotels & Hospitality",
        "Construction"
      ],
      "price25": "$99.98",
      "old25": "$131.98",
      "price50": "$189.98",
      "old50": "$235.98",
      "save": "$46",
      "url": "bundles.html"
    },
    {
      "name": "Automotive, Logistics & Agencies",
      "desc": "Bundle of Automotive + Logistics & Transportation + Agencies & Business Services datasets. Save up to $44.",
      "includes": [
        "Automotive",
        "Logistics & Transportation",
        "Agencies & Business Services"
      ],
      "price25": "$99.98",
      "old25": "$137.98",
      "price50": "$179.98",
      "old50": "$223.98",
      "save": "$44",
      "url": "bundles.html"
    },
    {
      "name": "Education, Events & Leisure",
      "desc": "Bundle of Education + Events & Leisure + Accounting & Finance datasets. Save up to $44.",
      "includes": [
        "Education",
        "Events & Leisure",
        "Accounting & Finance"
      ],
      "price25": "$99.98",
      "old25": "$129.98",
      "price50": "$169.98",
      "old50": "$213.98",
      "save": "$44",
      "url": "bundles.html"
    }
  ],
  "memberships": [
    {
      "name": "Basic Membership",
      "price": "$19.99",
      "url": "membership.html",
      "desc": "40% off Events & Leisure, Education & Training, and Construction datasets. Full CSV export."
    },
    {
      "name": "Pro Membership",
      "price": "$29.99",
      "url": "membership.html",
      "desc": "40% off 10 industries including Agencies & Business, Automotive, Logistics, Hotels & Hospitality, Home Services, Legal. Priority support."
    },
    {
      "name": "Max Membership",
      "price": "$49.99",
      "url": "membership.html",
      "desc": "40% off ALL 16 industries and ALL bundles. Bonus leads, priority access to new industries, priority support."
    }
  ],
  "pages": [
    {
      "title": "Home",
      "url": "index.html",
      "desc": "Buy verified B2B lead data by niche. CSV datasets with emails, phones, and websites across 16+ niches. One flat price, no credits, no software.",
      "keywords": "b2b leads, csv, lead data, verified, buy leads, dataset, niche"
    },
    {
      "title": "All Niches",
      "url": "industries.html",
      "desc": "Browse all 16 industry-specific datasets, each sourced and verified independently.",
      "keywords": "niches, industries, directory, verticals, datasets"
    },
    {
      "title": "About LeadsPitch",
      "url": "about.html",
      "desc": "Learn about LeadsPitch, the verified B2B lead data platform.",
      "keywords": "about, company, who we are, team"
    },
    {
      "title": "Bundles",
      "url": "bundles.html",
      "desc": "Buy multiple niche datasets together and save. Bundle pricing for 25K and 50K email packages.",
      "keywords": "bundles, save, combo, package, multi-niche"
    },
    {
      "title": "Membership",
      "url": "membership.html",
      "desc": "Memberships with 40% off datasets and bundles. Basic, Pro, and Max tiers.",
      "keywords": "membership, subscribe, 40% off, discount, subscription"
    },
    {
      "title": "FAQ",
      "url": "faq.html",
      "desc": "Frequently asked questions about LeadsPitch datasets, subscriptions, delivery, and refunds.",
      "keywords": "faq, help, questions, support, answers"
    },
    {
      "title": "Contact",
      "url": "contact.html",
      "desc": "Get in touch with the LeadsPitch team.",
      "keywords": "contact, email, support, reach out"
    },
    {
      "title": "Privacy Policy",
      "url": "privacy.html",
      "desc": "How LeadsPitch collects, uses, and shares information.",
      "keywords": "privacy, gdpr, ccpa, policy"
    },
    {
      "title": "Terms of Service",
      "url": "terms.html",
      "desc": "Terms and conditions for using LeadsPitch.",
      "keywords": "terms, conditions, legal"
    },
    {
      "title": "Refund Policy",
      "url": "refund.html",
      "desc": "LeadsPitch refund policy for datasets and subscriptions.",
      "keywords": "refund, money back, policy"
    }
  ],
  "faqs": [
    {
      "q": "How does LeadsPitch work?",
      "a": "You choose an industry and a plan on our Bundles page. Buy a single dataset and download it instantly. There's no software to log into or dashboard to search.",
      "url": "faq.html"
    },
    {
      "q": "Who is LeadsPitch for?",
      "a": "LeadsPitch is built for agency owners running outbound for clients, founders doing their own outreach, freelance recruiters, and small sales teams who want reliable business data without operating a full prospecting platform.",
      "url": "faq.html"
    },
    {
      "q": "How is LeadsPitch different from Apollo, ZoomInfo, or other sales intelligence platforms?",
      "a": "Apollo and ZoomInfo are software platforms with searchable dashboards and credit-based pricing. LeadsPitch doesn't require you to search for data or manage credits. You receive a finished dataset on a schedule instead of building one yourself inside a tool.",
      "url": "faq.html"
    },
    {
      "q": "Why does LeadsPitch offer subscriptions?",
      "a": "Business data goes stale quickly. People change roles, companies close, and contact details age. A subscription means you get a fresh dataset on a regular schedule. If you only need data once, a one-time purchase is also available.",
      "url": "faq.html"
    },
    {
      "q": "What happens after I subscribe?",
      "a": "You'll get access to your first dataset based on the industry you selected. Future datasets arrive automatically on your billing schedule. There's nothing else to configure.",
      "url": "faq.html"
    },
    {
      "q": "What happens after cancellation?",
      "a": "Billing stops, and you won't receive further datasets after your current billing period ends. Your subscription won't renew again unless you resubscribe.",
      "url": "faq.html"
    },
    {
      "q": "Can I upgrade or downgrade?",
      "a": "Yes. You can change your plan at any time from your account, and the change will apply going forward.",
      "url": "faq.html"
    },
    {
      "q": "Can I subscribe to multiple industries?",
      "a": "Yes. You can subscribe to more than one industry at the same time, or purchase one-time datasets across multiple verticals.",
      "url": "faq.html"
    },
    {
      "q": "Do unused records roll over?",
      "a": "No. Each subscription delivers a full dataset for the industry and plan you're on. There isn't a credit balance that carries over between months.",
      "url": "faq.html"
    },
    {
      "q": "How is a one-time purchase different from a subscription?",
      "a": "A subscription delivers a new dataset every billing period. A one-time purchase delivers a single dataset. Subscriptions include automatic renewals; one-time purchases don't.",
      "url": "faq.html"
    },
    {
      "q": "Can I buy the same dataset again later?",
      "a": "Yes. You can purchase the same industry dataset again at any time. Each purchase reflects the most current data available at that point.",
      "url": "faq.html"
    },
    {
      "q": "What information is included in a dataset?",
      "a": "Depending on the industry and plan, a dataset may include verified business email addresses, phone numbers, company name, owner or decision-maker name, job title, website, city, state, country, industry classification, company size, and LinkedIn company profile, where available. Not every field is available for every record.",
      "url": "faq.html"
    },
    {
      "q": "How accurate is the data?",
      "a": "We verify records before delivery, but no business dataset is ever 100% complete or error-free. Contact details change constantly. If you find a record that's inaccurate, let us know so we can look into it.",
      "url": "faq.html"
    },
    {
      "q": "Where does the data come from?",
      "a": "LeadsPitch datasets are compiled from publicly available and licensed sources related to business and professional activity. Each industry dataset is built specifically for that industry rather than filtered from one large, general database. For more detail, see our Privacy Policy .",
      "url": "faq.html"
    },
    {
      "q": "What industries are available?",
      "a": "LeadsPitch currently offers datasets across 19+ industries including Healthcare, Legal, Real Estate, Ecommerce, SaaS, B2B Companies, and more. Each dataset is built specifically for its industry. See the Niches page for details on each.",
      "url": "faq.html"
    },
    {
      "q": "Will more industries be added?",
      "a": "We expect to add industries over time. We'll announce new industries when they're actually available rather than promising a specific timeline in advance.",
      "url": "faq.html"
    },
    {
      "q": "How is data delivered?",
      "a": "Your dataset is delivered directly to your inbox on your billing schedule. There's no dashboard to log into to retrieve it.",
      "url": "faq.html"
    },
    {
      "q": "Which file formats are available?",
      "a": "Datasets are provided in common, easy-to-use file formats so you can open them in a spreadsheet or import them into a CRM without extra steps.",
      "url": "faq.html"
    },
    {
      "q": "When will I receive my dataset?",
      "a": "Your first dataset arrives shortly after you place your order. Subscribers receive follow-up datasets on their billing schedule. One-time purchases receive a single delivery. Exact timing can vary slightly.",
      "url": "faq.html"
    },
    {
      "q": "Which payment methods are accepted?",
      "a": "Payment methods accepted are shown at checkout when you purchase.",
      "url": "faq.html"
    },
    {
      "q": "Are subscriptions renewed automatically?",
      "a": "Yes. Subscriptions renew automatically at the end of each billing period unless you cancel before the renewal date. One-time purchases do not renew. Full terms are in our Terms of Service .",
      "url": "faq.html"
    },
    {
      "q": "Can invoices be provided?",
      "a": "Yes. If you need an invoice for your records, contact us and we'll provide one.",
      "url": "faq.html"
    },
    {
      "q": "How much does LeadsPitch cost?",
      "a": "Every option is one flat price with no credits or per-record charges. Pricing varies by industry and whether you choose a subscription or one-time purchase. See the Niches page for current rates.",
      "url": "faq.html"
    },
    {
      "q": "What if I'm charged but don't receive my dataset?",
      "a": "If you don't receive your dataset for a billing period you were charged for, contact us . We'll investigate and either redeliver the dataset or issue a refund for that period.",
      "url": "faq.html"
    },
    {
      "q": "How do I request a refund?",
      "a": "Use our Contact page with your account details and a description of the issue. We'll review your request individually.",
      "url": "faq.html"
    },
    {
      "q": "How does LeadsPitch handle GDPR and CCPA considerations?",
      "a": "We describe how we collect, use, and share information in our Privacy Policy , including sections specific to GDPR and CCPA. If you have rights under either regulation, you can exercise them by contacting us directly.",
      "url": "faq.html"
    },
    {
      "q": "How can someone request removal of their information?",
      "a": "Anyone whose business contact information appears in a LeadsPitch dataset can request removal by contacting us. We apply approved removal requests to future datasets going forward.",
      "url": "faq.html"
    },
    {
      "q": "How is personal information handled?",
      "a": "Information about you as a website visitor or customer, like your name, email, and billing details, is handled separately from the business datasets we sell. Full details are in our Privacy Policy .",
      "url": "faq.html"
    },
    {
      "q": "How do I contact support?",
      "a": "You can reach us through our Contact page or by filling out the form directly.",
      "url": "faq.html"
    },
    {
      "q": "How quickly can I expect a response?",
      "a": "We respond to support requests as quickly as we reasonably can. We don't want to promise a specific response time we might not consistently meet.",
      "url": "faq.html"
    },
    {
      "q": "How do I report an issue?",
      "a": "Use our Contact page with details of the issue, including your account information and what you're seeing. We'll look into it directly.",
      "url": "faq.html"
    },
    {
      "q": "Can I request a custom dataset?",
      "a": "Custom datasets aren't part of our current plans. If you have a specific need, contact us and let us know what you're looking for.",
      "url": "faq.html"
    },
    {
      "q": "What products does LeadsPitch offer?",
      "a": "LeadsPitch is a business data platform. We currently offer subscriptions and one-time dataset purchases across 19+ industries. We expect the ways we deliver business data to expand over time.",
      "url": "faq.html"
    },
    {
      "q": "Will LeadsPitch add custom sourcing or new data types?",
      "a": "We're always looking at ways to improve. When something new is ready, we'll explain it plainly on the website.",
      "url": "faq.html"
    },
    {
      "q": "Will pricing or plans change as LeadsPitch grows?",
      "a": "Plans and pricing may evolve as we add industries or offerings. Current subscribers would be notified of any changes affecting an active subscription before they take effect, as described in our Terms of Service .",
      "url": "faq.html"
    },
    {
      "q": "Will subscriptions always be available?",
      "a": "Yes. Subscriptions are a core part of what LeadsPitch does. Any future products would be additional ways to access business data, not a replacement for subscriptions.",
      "url": "faq.html"
    }
  ]
};
