// Generates a codebase dependency graph using madge.
// Outputs:
//   codegraph.json  — raw dependency map (module -> its imports)
//   CODEGRAPH.md    — a Mermaid flowchart that renders offline on GitHub,
//                     VS Code (Markdown Preview Mermaid Support), or mermaid.live
//
// Run: npm run graph
// For an SVG image instead, install Graphviz and run: npm run graph:svg

import madge from "madge";
import { writeFile } from "node:fs/promises";

const ROOTS = ["app", "components", "lib"];

const result = await madge(ROOTS, {
  fileExtensions: ["ts", "tsx"],
  tsConfig: "tsconfig.json",
});

const tree = result.obj();
const circular = result.circular();

await writeFile("codegraph.json", `${JSON.stringify(tree, null, 2)}\n`);

// Build a Mermaid flowchart from the dependency tree.
const nodeIds = new Map();
const idFor = (path) => {
  if (!nodeIds.has(path)) nodeIds.set(path, `n${nodeIds.size}`);
  return nodeIds.get(path);
};

for (const path of Object.keys(tree)) idFor(path);
for (const deps of Object.values(tree)) deps.forEach(idFor);

const lines = ["flowchart LR"];
for (const [path, id] of nodeIds) lines.push(`  ${id}["${path}"]`);
for (const [path, deps] of Object.entries(tree)) {
  for (const dep of deps) lines.push(`  ${idFor(path)} --> ${idFor(dep)}`);
}

const edgeCount = Object.values(tree).reduce((sum, deps) => sum + deps.length, 0);

const markdown = `# Codebase graph

Generated by \`npm run graph\` (madge). This Mermaid diagram renders on GitHub,
in VS Code with the "Markdown Preview Mermaid Support" extension, or by pasting
into https://mermaid.live. For an SVG image, install Graphviz and run
\`npm run graph:svg\`.

- Modules: ${nodeIds.size}
- Dependency links: ${edgeCount}
- Circular dependencies: ${circular.length === 0 ? "none" : circular.length}

\`\`\`mermaid
${lines.join("\n")}
\`\`\`
`;

await writeFile("CODEGRAPH.md", markdown);

console.log(`Modules: ${nodeIds.size}`);
console.log(`Dependency links: ${edgeCount}`);
if (circular.length === 0) {
  console.log("Circular dependencies: none");
} else {
  console.log(`Circular dependencies: ${circular.length}`);
  for (const cycle of circular) console.log(`  ${cycle.join(" -> ")}`);
}
console.log("Wrote codegraph.json and CODEGRAPH.md");
